{{- if .Values.serviceSecretKeys }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{.Values.name}}-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: {{.Values.name}}-secrets
    creationPolicy: Owner
  
  data:
  {{- $key := .Values.serviceSecretAwsName }}
  {{- range .Values.serviceSecretKeys }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ printf "%s" $key }}
      property: {{ . }}
  {{- end }}
{{- end }}