apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  labels:
    svc: {{ .Values.name }}
spec:
  selector:
    svc: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP