name: ci pipeline for service api
permissions:
  contents: write

on:
    push:
      branches:
        - main
      paths: 
        - mean-stack-example/server/**
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
           - name: Checkout code
             uses: actions/checkout@v3
             with:
                token: ${{ secrets.PAT }}

           - name: Log in to Docker Hub
             uses: docker/login-action@v2
             with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

           - name: build docker image
             run: docker build ./mean-stack-example/server -t ${{ secrets.DOCKER_HUB_USERNAME }}/simple-api:${{ github.sha }} 

           - name: push docker image to docker hub
             run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/simple-api:${{ github.sha }} 
    update-helm-values:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: update helm values file
              uses: mikefarah/yq@master
              with:
                cmd: yq -i '.dockerImage  = "${{ secrets.DOCKER_HUB_USERNAME }}/simple-api:${{ github.sha }}"' helm-charts/simple-api.yaml
            - name: commit and push updated values file
              run: |
               git config --global user.name "GitHub Actions"
               git config --global user.email "actions@github.com"
               git add .
               git commit -m "update: helm values file with new image tag ${IMAGE_TAG}"
               git push origin main